### ISSUE TITLE
Unable to play any song

### ISSUE THREAD

**Issue by jgoguen** [eeston/Jello#6]
iOS 17.3.1 on iPhone 15 Pro Max
Jello 0.0.36

I can load the list of songs in any album but nothing actually plays any songs. I can tap on a song in the list or the Play and Shuffle buttons and see UI effects to tell me the buttons have been pressed, but nothing ever starts playing. I can also tap the play icon at the very bottom, where it says "Not Playing", which also doesn't start anything but also gives me no indication it's been tapped.

I have three music libraries and have reproduced this with albums from all three libraries. On the Jellyfin server no logs are written so I'm assuming there's no errors. All music files are in MP3 format.

**Comment by eeston** [comment]
Thanks for the heads up @jgoguen 

I've come across an issue that may or may not be causing your problem. It's to do with loading artwork for a track.
When trying to find the artwork we use the track object to find it, but it isn't always available. So now I'm falling back to the album details to find the artwork. 

I have a fix built and ready to go...just waiting for the thumbs up from Apple.
Hopefully that solves the issue for you :)

**Comment by eeston** [comment]
Potential fix available in 0.0.38 which was just approved by Apple.

**Comment by jgoguen** [comment]
Partially fixed. Now I can play any three songs at first. After the third song, it attempts to load subsequent songs (the title and album art appears in the Now Playing bar and view) but the Play button turns into a spinner and never actually plays. It does stop playing the current song, so it seems Jello is expecting to be able to start streaming the file and start playing.

If I continue to try to switch to other songs it does eventually start to play a song (sometimes I switch just a few songs, sometimes I have to choose a lot of other songs), including ones it previously hung on. After that I get a few more songs successfully playing; as long as I stick to songs that have successfully played it will continue playing, but after 3-4 songs if I switch to a song that hasn't been played yet it hangs up again. I don't even need to attempt to load different songs each time, I can simply try loading the same song over and over again and it eventually starts to play. Restarting the app resets everything.

I also can't play any song without album art. Two of my music libraries are mostly songs with no album or track art, and some songs in my main Music library have no art. I can play songs from any library with album art but any song in any library with no art present isn't even attempted to be played. With album art, I can tap on the song and it'll play (or if it hangs, it at least appears in Now Playing bar), but songs with no art don't appear and don't interrupt the currently playing song at all.

**Comment by eeston** [comment]
Thanks for this. I'll have another look this weekend to see what else could be causing issues.

**Comment by eeston** [comment]
The issues around missing metadata should now be resolved in 0.0.44.

The issues around playback performance are related to a library I'm using for audio playback. I'm looking for a solution/alternative at the moment.

**Comment by jgoguen** [comment]
The only remaining issue here is how it stops playing songs for a while. I don’t know if you’re doing something different with the library this release, but it’s somewhat improved. Now it’s after 5-6 songs before it hangs while playing, and it’s faster to recover (I have to switch songs fewer times before it starts playing again).

Thanks for the hard work!

**Comment by anishmansuri** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
DontTrust0Verify, @r0ze117, @IntrovertedFL, @MetaXR, @nurrizkyimani, @ashvini-maurya, @ChrisKoler, @Soros1223, @belanenko, @robertvanvugt, @ripfreeworld, @BobLd, @liuzc, @Bintong, @Hrushi20, @solcik, @Da-MeLLo, @garymike, @nickofspades, @arpitgo4, @Crayon277, @dgktn, @zengxiaowen, @luizzuchinali, @Trytan6bz, @ncostamagna, @SatoshLee, @nomyfan, @jacobpclouse, @anasbaigmughal, @fabianoneumann, @Elib27, @ArdeshirV, @QingshuangZhu, @weizhongtan, @dejans11, @rebolyte, @lneicelis, @donaldxdonald, @jcards26, @claddyy, @Lyx09, @Pratik01-git, @zionfuo, @betterlife2022, @Tomz899, @humyna, @saminfante, @fidelsalgado, @jarbusSaber-Bjeoui, @0745dk, @aigcheng, @thieu1995, @interstellar-hitchhiker, @rajumariappan, @appsplash99, @Mateioo7, @BassirouNdao, @LiberlandHacker, @Barry0922, @mangosteenG, @migace, @renttrent, @toSTGW, @Georgepitt, @Grrr1Want2, @christophheise, @nafi-ansary, @JustCallMe-AK, @ekid, @tekitou, @red-butterfly, @brave3d, @wylu, @davidyakobovitch, @aviorian, @goamaral, @adamkrawczyk, @subzerofx, @kmicek, @Garana400, @parsecpp, @scharton, @belikovdev, @guoleijie, @robsn, @DawnLIU35, @Manifest1, @coderminer, @Rezga12, @SunshyZzz, @hh9515, @tienbt93, @mustorze, @vae520283995, @moorgrove, @Satoshi-Kusumoto, @swingboard, @Hawley66
